steps:
  # remove template files

  - remove: package.json
  - remove: readme.md

  # get project info

  - read: project_name
    prompt: 'Enter project name:'

  - read: project_description
    prompt: 'Enter project description:'

  - read: command_name
    prompt: 'Enter command name:'
    default:
      eval: '{{ project_name | skip: @tommy-mitchell/ | trim: -cli }}'

  - read: install_type
    prompt: 'Enter installation type:'
    choices:
      - 'dev'
      - 'global'
      - 'dep'

  # get computed variables

  - if:
      eval: '{{ install_type | matches: dev }}'
    steps:
      - read: install_node
        eval: 'node install --save-dev {{ project_name }}'
      - read: install_yarn
        eval: 'yarn add --dev {{ project_name }}'

  - if:
      eval: '{{ install_type | matches: global }}'
    steps:
      - read: install_node
        eval: 'node install --global {{ project_name }}'
      - read: install_yarn
        eval: 'yarn global add {{ project_name }}'

  - if:
      eval: '{{ install_type | matches: dep }}'
    steps:
      - read: install_node
        eval: 'node install {{ project_name }}'
      - read: install_yarn
        eval: 'yarn add {{ project_name }}'

  # setup project

  - update: src/cli.ts
  - update: test/test.ts

  - copy: package.tmplr.json
    to: package.json

  - copy: readme.tmplr.md
    to: readme.md

  # finish

  - remove: .tmplr.yml
  - remove: package.tmplr.json
  - remove: readme.tmplr.md
