steps:
  # remove template files

  - remove: package.json
  - remove: readme.md

  # get project info

  - read: project_name
    prompt: 'Enter project name:'
    default:
      from: filesystem.rootdir

  - read: project_description
    prompt: 'Enter project description:'

  - read: command_name
    prompt: 'Enter command name:'
    default:
      eval: '{{ project_name | skip: @tommy-mitchell/ | trim: -cli }}'

  - read: install_type
    prompt: 'Enter installation type:'
    choices:
      - 'dev'
      - 'global'
      - 'dep'

  - read: include_dot_vscode
    prompt: 'Include .vscode folder?'
    choices:
      - 'Yes'
      - 'No'

  - read: include_test_fixtures
    prompt: 'Include test fixtures?'
    choices:
      - 'Yes'
      - 'No'

  # get computed variables

  - if:
      eval: '{{ install_type | matches: dev }}'
    steps:
      - read: install_node
        eval: 'npm install --save-dev {{ project_name }}'
      - read: install_yarn
        eval: 'yarn add --dev {{ project_name }}'

  - if:
      eval: '{{ install_type | matches: global }}'
    steps:
      - read: install_node
        eval: 'npm install --global {{ project_name }}'
      - read: install_yarn
        eval: 'yarn global add {{ project_name }}'

  - if:
      eval: '{{ install_type | matches: dep }}'
    steps:
      - read: install_node
        eval: 'npm install {{ project_name }}'
      - read: install_yarn
        eval: 'yarn add {{ project_name }}'

  # setup project

  - if:
      eval: '{{ include_dot_vscode | matches: No }}'
    steps:
      - remove: ./template/.vscode

  - if:
      eval: '{{ include_test_fixtures | matches: Yes }}'
    steps:
      - copy: ./template/test-fixtures/**/*
        to: ./test
        include hidden: true
      - remove: ./template/test-fixtures
      - remove: ./template/test
    else:
      steps:
        - copy: ./template/test/**/*
          to: ./test
          include hidden: true
        - remove: ./template/test
        - remove: ./template/test-fixtures

  - copy: ./template/**/*
    to: ./
    include hidden: true

  # finish

  - remove: ./template/**/*
    include hidden: true

  # temporarily specify folders to remove (loreanvictor/tmplr#15)
  - remove: ./template/.github
  - remove: ./template/.vscode
  - remove: ./template/src
  - remove: ./template

  - remove: .tmplr.yml
